#!/usr/bin/env python3
import argparse

from flask import Flask

app = Flask(__name__)
from src.modules.apache_server import apache_server
from src.modules.configure import configure
from src.modules.php_application import deploy_php


@app.route('/')
def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "operation",
        type=str,
        choices=["deploy", "configure"]
    )
    parser.add_argument(
        "--module",
        type=str,
        choices=["php-application", "apache"],
    )
    parser.add_argument(
        "--file",
        type=str,
        required=True
    )
    args = parser.parse_args()

    file = args.file
    if args.operation == "deploy":
        module = args.module
        if not module:
            print("Must specify module. Try again and specify module name.")
        elif module == "php-application":
            deploy_php(file)
        elif module == "apache":
            apache_server(file)
    elif args.operation == "configure":
        configure(file)


main()
